import { Router } from "express";
import { z } from "zod";
import { requireAuth } from "../middleware/auth";
import { KitModel } from "../models/Kit";
import { buildKit, inputHash } from "../services/pipeline";
import { checkCoverage } from "@prep-kit/core";
const router=Router(); router.use(requireAuth);
const createSchema=z.object({jd:z.string().min(2).max(100000),company_url:z.string().url(),days:z.number().int().min(1).max(365)});
router.get("/",async(req,res,next)=>{try{const kits=await KitModel.find({userId:req.userId}).sort({createdAt:-1}).select("_id status input kit.source kit.createdAt error");res.json({kits})}catch(e){next(e)}});
router.get("/:id",async(req,res,next)=>{try{const kit=await KitModel.findOne({_id:req.params.id,userId:req.userId}); if(!kit)return res.status(404).json({error:{code:"NOT_FOUND",message:"Kit not found"}});res.json({kit})}catch(e){next(e)}});
router.post("/",async(req,res,next)=>{try{const input=createSchema.parse(req.body); const hash=inputHash(input); const existing=await KitModel.findOne({userId:req.userId,inputHash:hash,status:"ready"}); if(existing)return res.status(200).json({kit:existing,reused:true}); const record=await KitModel.create({userId:req.userId,input,inputHash:hash,status:"generating",kit:{},edits:[],progress:0,progressStep:"Queued"}); void buildKit(input,(step,percent)=>{KitModel.updateOne({_id:record._id},{$set:{progress:percent,progressStep:step}}).exec().catch(()=>{});}).then(async kit=>{record.kit=kit;record.baseKit=structuredClone(kit);record.status="ready";record.progress=100;record.progressStep="Complete";await record.save();}).catch(async e=>{record.status="failed";record.error=e.message;record.progressStep="Failed";await record.save();}); res.status(202).json({kit:record,reused:false});}catch(e){next(e)}});
router.patch("/:id",async(req,res,next)=>{try{const kit=await KitModel.findOne({_id:req.params.id,userId:req.userId}); if(!kit)return res.status(404).json({error:{code:"NOT_FOUND",message:"Kit not found"}}); if(req.body.kit){kit.kit=req.body.kit; kit.kit.coverage.uncovered_requirement_ids=checkCoverage(kit.kit.role.requirements,kit.kit.questions); kit.markModified("kit"); await kit.save();} res.json({kit})}catch(e){next(e)}});

router.post("/:id/regenerate",async(req,res,next)=>{try{const record=await KitModel.findOne({_id:req.params.id,userId:req.userId});if(!record)return res.status(404).json({error:{code:"NOT_FOUND",message:"Kit not found"}});const section=z.object({section:z.enum(["company_brief","technical","behavioural","system-design","company-fit","schedule"])}).parse(req.body).section;const input=record.input as any;const fresh=await buildKit({jd:input.jd,company_url:input.company_url,days:input.days});const current=record.kit as any;const base=record.baseKit as any; if(section==="company_brief") current.company_brief=fresh.company_brief; else if(section==="schedule") current.schedule=fresh.schedule; else {const category=section; const oldBase=(base.questions||[]).filter((q:any)=>q.category===category); const currentQs=(current.questions||[]); const currentById=new Map(currentQs.map((q:any)=>[q.id,q])); const baseIds=new Set(oldBase.map((q:any)=>q.id)); const regenerated=fresh.questions.filter((q:any)=>q.category===category); const merged=regenerated.map((q:any)=>{const currentQ=currentById.get(q.id); const baseQ=oldBase.find((x:any)=>x.id===q.id); return currentQ && baseQ && JSON.stringify(baseQ)!==JSON.stringify(currentQ) ? currentQ : q;}); const userAdded=currentQs.filter((q:any)=>q.category===category&&!baseIds.has(q.id)); current.questions=[...currentQs.filter((q:any)=>q.category!==category),...merged,...userAdded]; current.coverage.uncovered_requirement_ids=checkCoverage(current.role.requirements,current.questions); } current.coverage.passes=Math.max(current.coverage.passes||1,2);record.kit=current;record.baseKit=fresh;record.markModified("kit");record.markModified("baseKit");await record.save();res.json({kit:record})}catch(e){next(e)}});
router.post("/:id/practice",async(req,res,next)=>{try{const kit=await KitModel.findOne({_id:req.params.id,userId:req.userId});if(!kit)return res.status(404).json({error:{code:"NOT_FOUND",message:"Kit not found"}}); const {flashcardId,confidence}=req.body; if(!kit.practice)kit.practice={}; kit.practice[flashcardId]={confidence:Number(confidence),seenAt:new Date().toISOString()}; kit.markModified("practice"); await kit.save();res.json({practice:kit.practice});}catch(e){next(e)}});
export default router;
